language: python
python:
  - "2.7"

install:
  - sudo apt-get update
  - sudo apt-get install libpq-dev libavahi-compat-libdnssd-dev
  - pip install -r requirements.txt

script:
  - python manage.py rebuild
  - python manage.py test
  - flake8 pubbot

